// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package gui

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"ar": &dictionary{index: arIndex, data: arData},
		"en": &dictionary{index: enIndex, data: enData},
		"es": &dictionary{index: esIndex, data: esData},
		"sv": &dictionary{index: svIndex, data: svData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s\nMeeting ID: %s%%0D%%0A":          7,
	"A valid port is between 1 and 65535": 114,
	"Accept":                              25,
	"Allow the host to automatically join a newly created meeting": 103,
	"An error occurred\n\n%s":                                      12,
	"Are you sure you want to do this action?":                     26,
	"Are you sure you want to end this meeting?":                   27,
	"Are you sure you want to leave this meeting?":                 28,
	"Automatically join a meeting":                                 29,
	"Automatically join this meeting":                              104,
	"Automatically join this meeting when starting it":             105,
	"Be very careful. This information is sensitive and could potentially contain very private information. Only turn on these settings if you absolutely need it for debugging.": 106,
	"Browse": 30,
	"By clicking Yes, this meeting will end.":       31,
	"By clicking Yes, you will leave this meeting.": 32,
	"Cancel": 21,
	"Check this option to automatically join every meeting you host": 107,
	"Choose your email service to send invitation":                   42,
	"Client binary location":                                         33,
	"Configuration settings will be lost in the next session":        34,
	"Configure master password":                                      35,
	"Configured Mumble port is not valid: %s":                        98,
	"Confirmation":                   36,
	"Connecting, please wait...":     37,
	"Continue":                       38,
	"Copy Invitation":                39,
	"Copy Meeting ID":                40,
	"Copy URL":                       41,
	"Debugging":                      43,
	"Default Email":                  44,
	"Encrypt the configuration file": 45,
	"End this meeting":               108,
	"End this meeting for all":       109,
	"Error":                          0,
	"Finish":                         46,
	"General":                        47,
	"Gmail":                          48,
	"Host a new meeting":             49,
	"Host meeting":                   51,
	"Hosting":                        50,
	"If you backup the configuration file, we will reset the settings and continue normally. If the configuration file is encrypted, then we will ask you for a password to encrypt the new settings file.": 110,
	"If you disable this option, anyone could read your configuration settings":          19,
	"If you set this option to a file name, low level information will be logged there.": 52,
	"Invalid configuration file":                53,
	"Invalid password. Please, try again.":      54,
	"Invite others":                             55,
	"Join":                                      56,
	"Join Wahay Meeting":                        6,
	"Join a meeting":                            57,
	"Join meeting":                              58,
	"Join the meeting":                          111,
	"Join this meeting":                         112,
	"Keep configuration file when Wahay closes": 59,
	"Leave":              60,
	"Leave this meeting": 61,
	"Log debug info":     62,
	"Log debug output to the selected log file. If no file is selected then the log output will be written to the default log file.": 113,
	"Master password":                63,
	"Meeting ID":                     64,
	"Meeting ID:":                    65,
	"Meeting password":               66,
	"Mumble":                         67,
	"No, cancel":                     68,
	"Now you are hosting a meeting.": 69,
	"Open":                           22,
	"Open file":                      20,
	"Outlook":                        70,
	"Password":                       71,
	"Please enter the master password for the configuration file.":              72,
	"Please join the Wahay meeting with the following details:%%0D%%0A%%0D%%0A": 101,
	"Port":                               73,
	"Port out of range":                  74,
	"Raw log file":                       75,
	"Repeat the password":                76,
	"Save changes":                       77,
	"Security":                           78,
	"Settings":                           79,
	"Show":                               80,
	"Something went wrong: %s":           1,
	"Specify a password for the meeting": 81,
	"Start Meeting":                      9,
	"Start Meeting & Join":               8,
	"Start meeting":                      82,
	"The Meeting ID cannot be blank":     11,
	"The Mumble process is down":         10,
	"The error message":                  83,
	"The invitation email has been copied to the clipboard": 100,
	"The meeting ID has been copied to the clipboard":       5,
	"The meeting ID is invalid":                             14,
	"The meeting can't be closed: %s":                       3,
	"The onion service can't be deleted: %s":                4,
	"This action cannot be undone":                          84,
	"Toggle password visibility":                            85,
	"Type the Meeting ID (normally a .onion address)":       115,
	"Type the password":                                     86,
	"Type the password to join the meeting":                 87,
	"Type your preferred screen name":                       88,
	"Type your screen name":                                 89,
	"Username":                                              90,
	"Wahay is ready to use":                                 91,
	"We have detected that the configuration file is invalid or corrupted. Do you want to make a copy (backup) of it and continue?": 92,
	"We've found errors": 24,
	"Welcome":            93,
	"When this option is checked, the configuration settings will be stored in the device.": 94,
	"Yahoo Mail":                     95,
	"Yes, back it up &amp; continue": 116,
	"Yes, confirm":                   96,
	"You will not be asked for this password again until you restart Wahay.": 97,
	"enter a password at least 6 characters long":                            102,
	"enter the password confirmation":                                        17,
	"internal Tor instance has already been closed":                          99,
	"passwords do not match":                                                 18,
	"please enter a valid password":                                          16,
	"the Mumble client can not be used because: %s":                          15,
	"the provided meeting ID is invalid: \n\n%s":                             13,
	"tor can't be used":                                                      23,
	"we couldn't start the meeting":                                          2,
}

var arIndex = []uint32{ // 118 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x0000001a, 0x00000027,
	0x00000034, 0x00000041, 0x0000004e, 0x0000005b,
	0x00000068, 0x00000075, 0x00000082, 0x0000008f,
	0x0000009c, 0x000000a9, 0x000000b6, 0x000000c3,
	0x000000d0, 0x000000dd, 0x000000ea, 0x000000f7,
	0x00000104, 0x00000111, 0x0000011e, 0x0000012b,
	0x00000138, 0x00000145, 0x00000152, 0x0000015f,
	0x0000016c, 0x00000179, 0x00000186, 0x00000193,
	// Entry 20 - 3F
	0x000001a0, 0x000001ad, 0x000001ba, 0x000001c7,
	0x000001d4, 0x000001e1, 0x00000211, 0x0000021e,
	0x0000022b, 0x00000238, 0x00000245, 0x00000252,
	0x0000025f, 0x0000026c, 0x00000279, 0x00000286,
	0x00000293, 0x000002a0, 0x000002ad, 0x000002ba,
	0x000002c7, 0x000002d4, 0x000002e1, 0x000002ee,
	0x000002fb, 0x00000308, 0x00000315, 0x00000322,
	0x0000032f, 0x0000033c, 0x00000349, 0x00000356,
	// Entry 40 - 5F
	0x00000363, 0x00000370, 0x0000037d, 0x0000038a,
	0x00000397, 0x000003a4, 0x000003b1, 0x000003be,
	0x000003cb, 0x000003d8, 0x000003e5, 0x000003f2,
	0x000003ff, 0x0000040c, 0x00000419, 0x00000426,
	0x00000433, 0x00000440, 0x0000044d, 0x0000045a,
	0x00000467, 0x00000474, 0x00000481, 0x0000048e,
	0x0000049b, 0x000004a8, 0x000004b5, 0x000004c2,
	0x000004cf, 0x000004dc, 0x000004e9, 0x000004f6,
	// Entry 60 - 7F
	0x00000503, 0x00000510, 0x0000051d, 0x0000051d,
	0x0000051d, 0x0000051d, 0x0000051d, 0x0000051d,
	0x0000051d, 0x0000051d, 0x0000051d, 0x0000051d,
	0x0000051d, 0x0000051d, 0x0000051d, 0x0000051d,
	0x0000051d, 0x0000051d, 0x0000051d, 0x0000051d,
	0x0000051d, 0x0000051d,
} // Size: 496 bytes

const arData string = "" + // Size: 1309 bytes
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02الاتصال الرجاء الانتظار...\x02TRANSLATE ME\x02TRANSL" +
	"ATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME"

var enIndex = []uint32{ // 118 elements
	// Entry 0 - 1F
	0x00000000, 0x00000006, 0x00000022, 0x00000040,
	0x00000063, 0x0000008d, 0x000000bd, 0x000000d0,
	0x000000ee, 0x00000103, 0x00000111, 0x0000012c,
	0x0000014b, 0x00000164, 0x00000190, 0x000001aa,
	0x000001db, 0x000001f9, 0x00000219, 0x00000230,
	0x0000027a, 0x00000284, 0x0000028b, 0x00000290,
	0x000002a2, 0x000002b5, 0x000002bc, 0x000002e5,
	0x00000310, 0x0000033d, 0x0000035a, 0x00000361,
	// Entry 20 - 3F
	0x00000389, 0x000003b7, 0x000003ce, 0x00000406,
	0x00000420, 0x0000042d, 0x00000448, 0x00000451,
	0x00000461, 0x00000471, 0x0000047a, 0x000004a7,
	0x000004b1, 0x000004bf, 0x000004de, 0x000004e5,
	0x000004ed, 0x000004f3, 0x00000506, 0x0000050e,
	0x0000051b, 0x0000056e, 0x00000589, 0x000005ae,
	0x000005bc, 0x000005c1, 0x000005d0, 0x000005dd,
	0x00000607, 0x0000060d, 0x00000620, 0x0000062f,
	// Entry 40 - 5F
	0x0000063f, 0x0000064a, 0x00000656, 0x00000667,
	0x0000066e, 0x00000679, 0x00000698, 0x000006a0,
	0x000006a9, 0x000006e6, 0x000006eb, 0x000006fd,
	0x0000070a, 0x0000071e, 0x0000072b, 0x00000734,
	0x0000073d, 0x00000742, 0x00000765, 0x00000773,
	0x00000785, 0x000007a2, 0x000007bd, 0x000007cf,
	0x000007f5, 0x00000815, 0x0000082b, 0x00000834,
	0x0000084a, 0x000008c8, 0x000008d0, 0x00000926,
	// Entry 60 - 7F
	0x00000931, 0x0000093e, 0x00000985, 0x000009b0,
	0x000009de, 0x00000a14, 0x00000a5a, 0x00000a86,
	0x00000ac3, 0x00000ae3, 0x00000b14, 0x00000bc0,
	0x00000bff, 0x00000c10, 0x00000c29, 0x00000cef,
	0x00000d00, 0x00000d12, 0x00000d91, 0x00000db5,
	0x00000de5, 0x00000e04,
} // Size: 496 bytes

const enData string = "" + // Size: 3588 bytes
	"\x02Error\x02Something went wrong: %[1]s\x02we couldn't start the meetin" +
	"g\x02The meeting can't be closed: %[1]s\x02The onion service can't be de" +
	"leted: %[1]s\x02The meeting ID has been copied to the clipboard\x02Join " +
	"Wahay Meeting\x02%[1]s\x0aMeeting ID: %[2]s%0D%0A\x02Start Meeting & Joi" +
	"n\x02Start Meeting\x02The Mumble process is down\x02The Meeting ID canno" +
	"t be blank\x02An error occurred\x0a\x0a%[1]s\x02the provided meeting ID " +
	"is invalid: \x0a\x0a%[1]s\x02The meeting ID is invalid\x02the Mumble cli" +
	"ent can not be used because: %[1]s\x02please enter a valid password\x02e" +
	"nter the password confirmation\x02passwords do not match\x02If you disab" +
	"le this option, anyone could read your configuration settings\x02Open fi" +
	"le\x02Cancel\x02Open\x02tor can't be used\x02We've found errors\x02Accep" +
	"t\x02Are you sure you want to do this action?\x02Are you sure you want t" +
	"o end this meeting?\x02Are you sure you want to leave this meeting?\x02A" +
	"utomatically join a meeting\x02Browse\x02By clicking Yes, this meeting w" +
	"ill end.\x02By clicking Yes, you will leave this meeting.\x02Client bina" +
	"ry location\x02Configuration settings will be lost in the next session" +
	"\x02Configure master password\x02Confirmation\x02Connecting, please wait" +
	"...\x02Continue\x02Copy Invitation\x02Copy Meeting ID\x02Copy URL\x02Cho" +
	"ose your email service to send invitation\x02Debugging\x02Default Email" +
	"\x02Encrypt the configuration file\x02Finish\x02General\x02Gmail\x02Host" +
	" a new meeting\x02Hosting\x02Host meeting\x02If you set this option to a" +
	" file name, low level information will be logged there.\x02Invalid confi" +
	"guration file\x02Invalid password. Please, try again.\x02Invite others" +
	"\x02Join\x02Join a meeting\x02Join meeting\x02Keep configuration file wh" +
	"en Wahay closes\x02Leave\x02Leave this meeting\x02Log debug info\x02Mast" +
	"er password\x02Meeting ID\x02Meeting ID:\x02Meeting password\x02Mumble" +
	"\x02No, cancel\x02Now you are hosting a meeting.\x02Outlook\x02Password" +
	"\x02Please enter the master password for the configuration file.\x02Port" +
	"\x02Port out of range\x02Raw log file\x02Repeat the password\x02Save cha" +
	"nges\x02Security\x02Settings\x02Show\x02Specify a password for the meeti" +
	"ng\x02Start meeting\x02The error message\x02This action cannot be undone" +
	"\x02Toggle password visibility\x02Type the password\x02Type the password" +
	" to join the meeting\x02Type your preferred screen name\x02Type your scr" +
	"een name\x02Username\x02Wahay is ready to use\x02We have detected that t" +
	"he configuration file is invalid or corrupted. Do you want to make a cop" +
	"y (backup) of it and continue?\x02Welcome\x02When this option is checked" +
	", the configuration settings will be stored in the device.\x02Yahoo Mail" +
	"\x02Yes, confirm\x02You will not be asked for this password again until " +
	"you restart Wahay.\x02Configured Mumble port is not valid: %[1]s\x02inte" +
	"rnal Tor instance has already been closed\x02The invitation email has be" +
	"en copied to the clipboard\x02Please join the Wahay meeting with the fol" +
	"lowing details:%0D%0A%0D%0A\x02enter a password at least 6 characters lo" +
	"ng\x02Allow the host to automatically join a newly created meeting\x02Au" +
	"tomatically join this meeting\x02Automatically join this meeting when st" +
	"arting it\x02Be very careful. This information is sensitive and could po" +
	"tentially contain very private information. Only turn on these settings " +
	"if you absolutely need it for debugging.\x02Check this option to automat" +
	"ically join every meeting you host\x02End this meeting\x02End this meeti" +
	"ng for all\x02If you backup the configuration file, we will reset the se" +
	"ttings and continue normally. If the configuration file is encrypted, th" +
	"en we will ask you for a password to encrypt the new settings file.\x02J" +
	"oin the meeting\x02Join this meeting\x02Log debug output to the selected" +
	" log file. If no file is selected then the log output will be written to" +
	" the default log file.\x02A valid port is between 1 and 65535\x02Type th" +
	"e Meeting ID (normally a .onion address)\x02Yes, back it up &amp; contin" +
	"ue"

var esIndex = []uint32{ // 118 elements
	// Entry 0 - 1F
	0x00000000, 0x00000006, 0x0000001d, 0x0000003d,
	0x00000062, 0x0000008f, 0x000000c3, 0x000000ec,
	0x00000111, 0x0000012c, 0x0000013e, 0x0000015d,
	0x00000186, 0x0000019f, 0x000001d3, 0x000001f5,
	0x00000226, 0x00000254, 0x00000283, 0x000002a1,
	0x000002ff, 0x0000030d, 0x00000316, 0x0000031c,
	0x00000331, 0x0000034d, 0x00000355, 0x00000387,
	0x000003bd, 0x000003ef, 0x00000424, 0x0000042d,
	// Entry 20 - 3F
	0x0000045e, 0x0000048e, 0x000004ac, 0x000004ee,
	0x0000050d, 0x0000051b, 0x0000053b, 0x00000545,
	0x00000558, 0x0000056e, 0x00000579, 0x000005be,
	0x000005ca, 0x000005df, 0x00000603, 0x0000060c,
	0x00000614, 0x0000061a, 0x00000637, 0x0000063f,
	0x00000653, 0x000006ba, 0x000006de, 0x00000709,
	0x00000719, 0x00000720, 0x00000736, 0x0000074b,
	0x00000781, 0x00000787, 0x0000079e, 0x000007c4,
	// Entry 40 - 5F
	0x000007d8, 0x000007ea, 0x000007fd, 0x00000818,
	0x0000081f, 0x0000082c, 0x00000853, 0x0000085b,
	0x00000867, 0x000008a9, 0x000008b0, 0x000008c6,
	0x000008db, 0x000008f1, 0x00000901, 0x0000090b,
	0x0000091b, 0x00000923, 0x00000950, 0x00000964,
	0x00000978, 0x0000099a, 0x000009be, 0x000009d5,
	0x00000a06, 0x00000a2d, 0x00000a4a, 0x00000a5c,
	0x00000a7a, 0x00000afc, 0x00000b07, 0x00000b5c,
	// Entry 60 - 7F
	0x00000b6c, 0x00000b7a, 0x00000bc3, 0x00000bf9,
	0x00000c0f, 0x00000c48, 0x00000ca3, 0x00000cd7,
	0x00000d2f, 0x00000d57, 0x00000d8c, 0x00000e40,
	0x00000ea6, 0x00000ebc, 0x00000edd, 0x00000fd9,
	0x00000fee, 0x00001005, 0x000010c3, 0x000010f6,
	0x00001137, 0x00001154,
} // Size: 496 bytes

const esData string = "" + // Size: 4436 bytes
	"\x02Error\x02Algo salió mal: %[1]s\x02no se pudo comenzar la reunión\x02" +
	"La reunión no se pudo cerrar: %[1]s\x02El servicio Onion no se pudo elim" +
	"inar: %[1]s\x02El ID de la reunion ha sido copiado al portapapeles\x02Un" +
	"irse a una reunión a travéz de Wahay\x02%[1]s\x0aID de la reunión: %[2]s" +
	"%0D%0A\x02Comenzar reunión y Unirse\x02Comenzar reunión\x02El proceso Mu" +
	"mble está caído\x02El ID de la reunión no puede ser vacío\x02Ocurrió un " +
	"error\x0a\x0a%[1]s\x02el ID de la reunión provisto es inválido: \x0a\x0a" +
	"%[1]s\x02El ID de la reunión es inválido\x02El cliente Mumble no se pued" +
	"e usar porque: %[1]s\x02por favor especifique una contraseña válida\x02e" +
	"specifique la confirmación de la contraseña\x02las contraseñas no coinci" +
	"den\x02Si deshabilita esta opción, cualquier persona podría leer los par" +
	"ámetros de configuración\x02Abrir archivo\x02Cancelar\x02Abrir\x02tor n" +
	"o se puede usar\x02Encontramos algunos errores\x02Aceptar\x02¿Está segur" +
	"o de que quieres hacer esta acción?\x02¿Está seguro de que quieres termi" +
	"nar esta reunión?\x02¿Está seguro de que quiere dejar esta reunión?\x02Ú" +
	"nase automáticamente a esta reunión al iniciarla\x02Examinar\x02Al hacer" +
	" clic en Sí, esta reunión finalizará.\x02Al hacer clic en Sí, saldrá de " +
	"esta reunión.\x02Ubicación del binario Mumble\x02Los ajustes de configur" +
	"ación se perderán en la próxima sesión\x02Configurar contraseña maestra" +
	"\x02Confirmación\x02Conectando, espere por favor...\x02Continuar\x02Copi" +
	"ar invitación\x02Copiar ID de reunión\x02Copiar URL\x02Elija su servicio" +
	" de correo electrónico para enviar la invitación.\x02Depuración\x02Email" +
	" predeterminado\x02Cifrar el archivo de configuración\x02Terminar\x02Gen" +
	"eral\x02Gmail\x02Organizar una nueva reunión\x02Hosting\x02Reunión de ac" +
	"ogida\x02Si establece esta opción en un nombre de archivo, la informació" +
	"n de bajo nivel se registrará allí.\x02Archivo de configuración inválido" +
	"\x02Contraseña invalida. Inténtalo de nuevo.\x02Invitar a otros\x02Unirs" +
	"e\x02Unirse a una reunión\x02Unirse a la reunión\x02Mantener el archivo " +
	"de configuración al cerrar Wahay\x02Salir\x02Salir de esta reunión\x02Re" +
	"gistrar información de depuración\x02Contraseña maestra\x02ID de la reun" +
	"ión\x02ID de la reunión:\x02Contraseña de la reunión\x02Mumble\x02No, ca" +
	"ncelar\x02Ahora estás organizando una reunión.\x02Outlook\x02Contraseña" +
	"\x02Ingrese la contraseña maestra para el archivo de configuración.\x02P" +
	"uerto\x02Puerto fuera de rango\x02Archivo de registros\x02Repita la cont" +
	"raseña\x02Guardar cambios\x02Seguridad\x02Configuraciones\x02Mostrar\x02" +
	"Especifique una contraseña para la reunión\x02Comience a reunirse\x02El " +
	"mensaje de error\x02Esta acción no se puede deshacer\x02Alternar visibil" +
	"idad de contraseña\x02Escribe la contraseña\x02Escriba la contraseña par" +
	"a unirse a la reunión\x02Escriba su nombre de usuario preferido\x02Escri" +
	"ba su nombre de usuario\x02Nombre de usuario\x02Wahay está listo para us" +
	"arse\x02Hemos detectado que el archivo de configuración no es válido o e" +
	"stá dañado. ¿Desea hacer una copia de seguridad y continuar?\x02Bienveni" +
	"do\x02Cuando esta opción está marcada, la configuración se guardará en e" +
	"l dispositivo.\x02Correo de Yahoo\x02Si, confirmar\x02No se le volverá a" +
	" solicitar esta contraseña hasta que reinicie Wahay.\x02El puerto config" +
	"urado para Mumble es inválido: %[1]s\x02tor no está definido\x02El corre" +
	"o de invitación ha sido copiado al portapapeles\x02Por favor únete a la " +
	"reunión a travéz de Wahay con los siguientes detalles:%0D%0A%0D%0A\x02es" +
	"pecifique una contraseña de mínimo 6 caracteres\x02Permita que el organi" +
	"zador se una automáticamente a una reunión cuando cree una nueva\x02Unir" +
	"se automáticamente a esta reunión\x02Únase automáticamente a esta reunió" +
	"n al iniciarla\x02Ten mucho cuidado. Esta información es confidencial y " +
	"podría contener información muy privada. Solo cambia esta configuración " +
	"si la necesita absolutamente para la depuración.\x02Marque esta opción p" +
	"ara unirse automáticamente a cada reunión creada en la sección del anfit" +
	"rión\x02Termina esta reunión\x02Termina esta reunión para todos\x02Si re" +
	"aliza una copia de seguridad del archivo de configuración, restablecerem" +
	"os la configuración y continuaremos normalmente. Si el archivo de config" +
	"uración está cifrado, le pediremos una contraseña para cifrar el nuevo a" +
	"rchivo de configuración.\x02Únete a la reunión\x02Únete a esta reunión" +
	"\x02Registre la salida de depuración en el archivo de registro seleccion" +
	"ado. Si no se selecciona ningún archivo, la salida del registro se escri" +
	"birá en el archivo de registro predeterminado.\x02El rango de puertos vá" +
	"lidos está entre 1 y 65535\x02Escriba la ID de la reunión (normalmente u" +
	"na dirección .onion)\x02Sí, respaldarlo y continuar"

var svIndex = []uint32{ // 118 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x0000001a, 0x00000027,
	0x00000034, 0x00000041, 0x0000004e, 0x0000005b,
	0x00000068, 0x00000075, 0x00000082, 0x0000008f,
	0x0000009c, 0x000000a9, 0x000000b6, 0x000000c3,
	0x000000d0, 0x000000dd, 0x000000ea, 0x000000f7,
	0x00000104, 0x00000111, 0x0000011e, 0x0000012b,
	0x00000138, 0x00000145, 0x00000152, 0x0000015f,
	0x0000016c, 0x00000179, 0x00000186, 0x00000193,
	// Entry 20 - 3F
	0x000001a0, 0x000001ad, 0x000001ba, 0x000001c7,
	0x000001d4, 0x000001e1, 0x000001fd, 0x0000020a,
	0x00000217, 0x00000224, 0x00000231, 0x0000023e,
	0x0000024b, 0x00000258, 0x00000265, 0x00000272,
	0x0000027f, 0x0000028c, 0x00000299, 0x000002a6,
	0x000002b3, 0x000002c0, 0x000002cd, 0x000002da,
	0x000002e7, 0x000002f4, 0x00000301, 0x0000030e,
	0x0000031b, 0x00000328, 0x00000335, 0x00000342,
	// Entry 40 - 5F
	0x0000034f, 0x0000035c, 0x00000369, 0x00000376,
	0x00000383, 0x00000390, 0x0000039d, 0x000003aa,
	0x000003b7, 0x000003c4, 0x000003d1, 0x000003de,
	0x000003eb, 0x000003f8, 0x00000405, 0x00000412,
	0x0000041f, 0x0000042c, 0x00000439, 0x00000446,
	0x00000453, 0x00000460, 0x0000046d, 0x0000047a,
	0x00000487, 0x00000494, 0x000004a1, 0x000004ae,
	0x000004bb, 0x000004c8, 0x000004d5, 0x000004e2,
	// Entry 60 - 7F
	0x000004ef, 0x000004fc, 0x00000509, 0x00000516,
	0x00000523, 0x00000530, 0x0000053d, 0x0000054a,
	0x00000557, 0x00000564, 0x00000571, 0x0000057e,
	0x0000058b, 0x00000598, 0x000005a5, 0x000005b2,
	0x000005bf, 0x000005cc, 0x000005d9, 0x000005e6,
	0x000005f3, 0x00000600,
} // Size: 496 bytes

const svData string = "" + // Size: 1536 bytes
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02Ansluter, var god vänta...\x02TRANSLATE ME\x02TRANSL" +
	"ATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRAN" +
	"SLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME\x02TRANSLATE ME" +
	"\x02TRANSLATE ME"

	// Total table size 12853 bytes (12KiB); checksum: C41194AF
